CREATE TABLE IF NOT EXISTS role(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(250) UNIQUE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

INSERT INTO role(title, created_at, updated_at) VALUES
    ('user', NOW(), NOW()),
    ('psychologist', NOW(), NOW()),
    ('admin', NOW(), NOW());

CREATE TABLE IF NOT EXISTS account(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(250) UNIQUE NOT NULL,
    password VARCHAR(250) NOT NULL,
    role_id INT REFERENCES role(id) ON DELETE CASCADE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS token(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT REFERENCES account(id) ON DELETE CASCADE,
    access_token VARCHAR(250) UNIQUE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_token(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_name VARCHAR(250) UNIQUE NOT NULL,
    token VARCHAR(250) UNIQUE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS telegram_connection(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT REFERENCES account(id) ON DELETE CASCADE,
    tg_user_id INT UNIQUE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
